### PR TITLE
Attempt to fix unexpected multiclick behavior

### LINKED ISSUE #314: Unexpected behavior when double/triple/N clicking a file in the MPQ Explorer
## Describe the bug
When a user double/triple/N clicks a file in the MPQ Explorer, the widget is constructed in an unexpected way

## To Reproduce
1. Open the MPQ Explorer
2. Navigate to a file
3. Click the file more than once

## Expected behavior
The expected behavior should be to generate a widget with the same elements as when generated after a single click

## Screenshots
Animation_2

## Desktop (please complete the following information):
 - OS: Windows 10
 - Go version go1.16.4 windows/amd64
 - Ryzen 5600X (Issue depends on system performance)

## Additional context
The weird part is that it does stop you from opening a second widget of the same file so it seems like the bug is that it will run the create widget method for each click prior to the widget being loaded
Might be tied to the the GIU widget id?

### PR DESCRIPTION
**Pull request by bbrucee**
By moving the editorManagerMutex lock from around the editors append to around the createEditor call, the behavior of multiple createEditor calls for a single file is corrected.

However, this may introduce data race issues for the editors append when used by the RestoreAppState calls. I am pushing hoping to generate discussion around this topic.

### CODE REVIEW

**Comment by gravestench** [comment]
What happens if you put the lock/unlock around both the append and the create?

**Comment by bbrucee** [comment]
> What happens if you put the lock/unlock around both the append and the create?

If you lock in both the append and the create with the same lock it would deadlock

**Comment by gravestench** [comment]
It's been a month without any objections being made, I'm fine with merging. We can file a new issue if this leads to a race condition that makes the app explode in another way.

**Can someone else verify this fix, please?**

I think my hardware is fast enough that I'm not able to launch multiple editors fast enough.

**Review by gravestench — APPROVED** [review]

**Review by gucio321 — APPROVED** [review]
app works fine, no described problem

**Pull request merged**
