### PR TITLE
palette editors: refactoring

### LINKED ISSUE #328: DAT palette editor needs a refactor
The current DAT palette editor implementation is slow, hard to use, and takes up a lot of visual real estate on the screen.

My gripes:
* when you open the palette editor, you can see the buttons rendering to the window
* editing a color is clunky, with 3 sliders for each color
* when you edit a color, the original widget disappears
* the editor displays colors in a grid of 256 buttons, which takes up a lot of screen space because of the automatic spacing

IMO, this needs a refactor.

https://user-images.githubusercontent.com/936440/124398170-2c9dac00-dcc9-11eb-8e68-fedd88f7ab44.mov

### PR DESCRIPTION
**Pull request by gucio321**
Hi there,
This reverts a part of #224.
Using a... huge set of `ImageButtonWidget`s isn't so effective. I decided to use an old palette image with click detector which opens an editor.

### CODE REVIEW

**Comment by gravestench** [comment]
I'm seeing strange behavior:
https://user-images.githubusercontent.com/936440/120947581-d0a92d00-c6f4-11eb-9dc8-8c490e80d26e.mov

**Comment by gucio321** [comment]
hmm, @gravestench thats really strange. it works fine on both my laptops with `Fedora`.
I removed unnecessary `go-func` in 7d3e1cb but I don't believe it will help.
could you run a [giu example for textures loading](https://github.com/AllenDang/giu/blob/master/examples/texturefiltering) and tell check if delay is also present.

**Review by gravestench — DISMISSED** [review]
This is so much better, good work.

https://user-images.githubusercontent.com/936440/124208791-2c20cd80-da9d-11eb-9d34-e6f1842b1f08.mov

**Comment by gravestench** [comment]
I've issued a PR against your fork which resolves build errors.

**Review by gravestench — CHANGES_REQUESTED** [review]
There are remnants of your previous implementation that don't make sense to have, like `state.mode`. You were initially using this to fully switch the entire contents of the editor window, which is not what you are doing anymore.

However, because you are still using this mode-switch logic, grid disappears while the color editor is visible. You can see this in the video I posted, the window in the background becomes small while the color editor is in the foreground.

The grid should still be visible when the color editor modal window is opened.

**Comment by gravestench** [comment]
There is a bug; after editing a color, the grid is not updated until you click on it.

https://user-images.githubusercontent.com/936440/124366321-c569f400-dc03-11eb-9fa6-25260b4a6fbc.mov

**Comment by gucio321** [comment]
@gravestench fixed

**Comment by gravestench** [comment]
Good job! looks like it's working.

https://user-images.githubusercontent.com/936440/124397527-23124500-dcc5-11eb-87a6-b80f3dfccc87.mov

**Review by gravestench — APPROVED** [review]

**Pull request merged**
