### PR TITLE
Palete editor

### LINKED ISSUE #83: Add editor features to Palette viewer
Depends on:
* https://github.com/OpenDiablo2/OpenDiablo2/issues/909
* #73

### PR DESCRIPTION
**Pull request by gucio321**
fixes #83

### CODE REVIEW

**Comment by gucio321** [comment]
will work properly after merging OpenDiablo2/OpenDiablo2#1088

**Comment by gucio321** [comment]
I'm going to split palettegridwidget into:
- palette grid editor widget to edit palette grid
- palette grid widget to display grid

**Comment by gucio321** [comment]
these widgets will be used in my next PR for palette transform (PL2) editor

**Comment by gucio321** [comment]
> will work properly after merging [OpenDiablo2/OpenDiablo2#1088](https://github.com/OpenDiablo2/OpenDiablo2/pull/1088)

now works fine

**Review by essial — APPROVED** [review]

**Pull request merged**
